version: "3"

services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile # Dockerfileのパス
    image: fastapi-tutorial # イメージ名を指定
    container_name: fastapi_container # コンテナ名
    ports:
      - "8080:8000" # ホストの8080ポートをコンテナの8000ポートにマッピング
    volumes:
      - ${MY_APP_PATH}/app:/app # ホストのディレクトリをコンテナにマウント
